# Generated by Django 4.2.8 on 2023-12-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
