# Generated by Django 4.2.8 on 2023-12-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
